In [ ]:
#Added github

In [1]:
import pandas as pd
import numpy as np

In [3]:
x1=np.random.randint(low=1,high=20,size=(50,))
print(x1)

x2=np.random.randint(low=1,high=20,size=(50,))
print(x2)

[ 4  8 19  1  7  3  5 18  3 15  5 11  8 12  7  3 18 13  1 15  8  6  1 11
 10  7  1 16 12  3 11  2  7  2 13 19  2 15  6 19  7  2  7 16  6 17 10  8
 15 19]
[14  9  4  9  5  7  5 17 16  2 11 17 16 11 16  9 10  9 18  4 12  4  8 15
 11  3 12  5 14  4  4 12 18 12  6 11 10 18 17  8 13  4  1  7 19 17  7 14
  4 14]


In [4]:
y=3+2*x1-4*x2+np.random.random((50,))

In [5]:
y

array([-44.73289949, -16.59095494,  25.84417577, -30.23765561,
        -2.91946855, -18.60288349,  -6.36315426, -28.70238842,
       -54.5754125 ,  25.00686658, -30.93109009, -42.77852764,
       -44.58958537, -16.59362887, -46.26778286, -26.74691647,
        -0.94758028,  -6.94547231, -66.2150023 ,  17.61197956,
       -28.86012041,  -0.60146742, -26.75892067, -34.97551941,
       -20.12978019,   5.8054743 , -42.57006075,  15.71903094,
       -28.79107219,  -6.02378003,   9.92747344, -40.86680002,
       -54.97837007, -40.48673488,   5.21387322,  -2.40519242,
       -32.11429364, -38.34354321, -52.96798369,   9.27349109,
       -34.33205633,  -8.27317416,  13.11933098,   7.77648323,
       -60.72225278, -30.82203261,  -4.85328578, -36.60161702,
        17.04444642, -14.53973493])

In [6]:
x1

array([ 4,  8, 19,  1,  7,  3,  5, 18,  3, 15,  5, 11,  8, 12,  7,  3, 18,
       13,  1, 15,  8,  6,  1, 11, 10,  7,  1, 16, 12,  3, 11,  2,  7,  2,
       13, 19,  2, 15,  6, 19,  7,  2,  7, 16,  6, 17, 10,  8, 15, 19])

In [7]:
x2

array([14,  9,  4,  9,  5,  7,  5, 17, 16,  2, 11, 17, 16, 11, 16,  9, 10,
        9, 18,  4, 12,  4,  8, 15, 11,  3, 12,  5, 14,  4,  4, 12, 18, 12,
        6, 11, 10, 18, 17,  8, 13,  4,  1,  7, 19, 17,  7, 14,  4, 14])

In [8]:


x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})

w=[np.zeros(x.shape[1])]

In [9]:
x.head()

intercept  x1  x2
0          1   4  14
1          1   8   9
2          1  19   4
3          1   1   9
4          1   7   5

In [10]:
print(x.shape)
print(x.shape)
w

(50, 3)
(50, 3)


[array([0., 0., 0.])]

In [19]:
#calculating predicted y 
# (beta) * X
def myprediction(features,weights):

    predictions=np.dot(features,weights)  #### np.dot matrix mupltiplication
    return(predictions)

myprediction(x,w)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)
myerror(y,x,w)

array([-32.25270456,  -2.22910966, -16.61329566, -10.32575381,
       -58.5282721 , -14.65412997, -24.30121055,  -6.84431307,
         7.90995888, -50.64487106, -42.77095865,  -2.5202918 ,
       -54.17237533, -12.38879974, -56.22731389, -10.49155005,
        37.67018371, -38.04872573,   1.55180952, -22.7587504 ,
       -40.26299319, -22.09560021,  11.47003004,   9.36272541,
       -32.96748793,   7.6721027 ,  13.98697261,   3.62381638,
       -24.98167593,   5.05455528, -10.7423047 ,  27.41887247,
       -64.72703441, -34.57978806, -56.55437763,  13.01056649,
       -12.99923066,  25.85315077,  31.41052658, -46.59502706,
       -58.21117849,   7.32760529,  -8.41432889, -18.69307321,
       -22.282829  ,  13.81220703,  -8.55052025, -14.31781354,
        -0.40950621, -64.94858495])

In [25]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)  #### Just like summation of (y - y^)**2 
    return(cost)

mycost(y,x,w)


46909.857658733614

In [ ]:
temp = mycost(y,x,w)

In [28]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

print(gradient(y,x,w))


array([  780.97069714,  4762.55217302, 14783.97085545])

In [36]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        #weights[0] -=10*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        if i%1000==0:
            print(mycost(target,features,weights),weights)
    return(weights)

my_lr(y,x,0.0001)

21216.023860395715 [ 0.11319359 -0.47625522 -1.47839709]
3.4989780859519195 [ 3.61065427  1.99512889 -4.00622881]
3.4988546968575043 [ 3.6151951   1.99490018 -4.0064024 ]
3.4988546966096257 [ 3.61520154  1.99489985 -4.00640264]
3.4988546966096354 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 -4.00640264]
3.498854696609616 [ 3.61520155  1.99489985 

array([ 3.61520155,  1.99489985, -4.00640264])

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
lr=LinearRegression()

In [40]:
x.shape

(50, 3)

In [42]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [43]:
lr.coef_

array([ 1.99489985, -4.00640264])

In [44]:
lr.intercept_

3.6152015487350173